#!/bin/bash
while true;
do
	read line
	echo "$line" > task5_pipe

	if [[ "$line" == "QUIT" ]];
	then
		echo "Finish!"
		exit 0
	fi

	if [[ "$line" != [0-9]* && "$line" != "+" && "$line" != "*" ]];
	then 
		echo "Wrong input data"
		exit 1
	fi
done

