#!/bin/bash

echo $$ > .pid
number=1
value=""

EXIT()
{
	echo "Exiting"
	exit 0
}

PLUS()
{
	value="+"
}

MULTI()
{
	value="*"
}

trap 'EXIT' SIGTERM
trap 'PLUS' USR1
trap 'MULTI' USR2

while true;
do
	case "$value" in
		"+")
			number=$((number + 2))
			;;
		"*")
			number=$((number * 2))
			;;
	esac
	echo $number
	sleep 1
done
