#!/bin/bash
fiecho "Choose the command: "
echo "1 = nano"
echo "2 = vi"
echo "3 = links"
echo "4 = exit"
read a
case $a in 
1)
/usr/bin/nano
;;
2) 
/usr/bin/vi
;;
3)
usr/bin/links
;;
4)
echo "EXIT"
exit 0
;;
esac


