#!/bin/bash
date=$(date '+%d.%m.%y_%H:%M:%S')
mkdir ~/test && { echo "catalog test was created successfully" > ~/report ; touch ~/test/$date ; }
ping net_nikogo.ru || echo "${date} ERROR HOST" >> ~/report



